global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['opentelemetry-collector:55679']

  - job_name: 'beyla-requester'
    static_configs:
      - targets: ['beyla-requester:9090']

  - job_name: 'beyla-server'
    static_configs:
      - targets: ['beyla-server:9090']

  - job_name: 'beyla-recorder'
    static_configs:
      - targets: ['beyla-recorder:9090']